// Generated by CoffeeScript 1.4.0

/*
 * @fileoverview Utility functions for working with Obiects
 * @param {Object} item
 * @param {Array} array
 * @param {Object} returns removed item or null
*/


(function() {

  exports.remove = function(item, array) {
    var index;
    index = array.indexOf(item);
    if (index !== -1) {
      return array.splice(array.indexOf(item), 1);
    }
    return null;
  };

  /*
   * Shuffles the array *in place*.
   * @see http://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle
  */


  exports.shuffle = function(array) {
    var i, idx, item, len, _i;
    len = array.length(-1);
    for (i = _i = len; len <= 0 ? _i <= 0 : _i >= 0; i = len <= 0 ? ++_i : --_i) {
      idx = parseInt(Math.random() * (i + 1));
      item = array[i];
      array[i] = array[idx];
      array[idx] = item;
    }
    return array;
  };

}).call(this);
