// Generated by CoffeeScript 1.4.0

/*
 * @fileoverview A seedable random-number generator. Especially
 * useful in conjunction with the noise generator in `gamejs/utils/noise`.
 *
*/


/* @ignore
*/


(function() {
  var Alea, Mash;

  Mash = exports.Mash = function() {
    var n;
    n = 0xefc8249d;
    this.hash = function(data) {
      var h, i, _i, _ref;
      data = data.toString();
      for (i = _i = 0, _ref = data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        n += data.charCodeAt(i);
        h = 0.02519603282416938 * n;
        n = h >>> 0;
        h -= n;
        h *= n;
        n = h >>> 0;
        h -= n;
        n += h * 0x100000000;
      }
      return (n >>> 0) * 2.3283064365386963e-10;
    };
    this.version = 'Mash 0.9';
    return this;
  };

  /*
   * A seedable pseudo-random number generator.
   * @param {Number|String} seed the seed for generating the numbers
   *
   * @usage
   *  prng = require('gamejs/utils/prng')
   *  seed = 'gamejs'
   *  alea = new prng.Alea(seed)
   *  alea.random() # 0.6765871671959758
   *  alea.random() # 0.15881546027958393
   *
   *  # generator with the same seed will generate the same sequence
   *  # of numbers:
   *  aleaTwo = new prng.Alea(seed)
   *  aleaTwo.random() # 0.6765871671959758
   *  aleaTwo.random() # 0.15881546027958393
  */


  Alea = exports.Alea = function() {
    var args, c, i, mash, s0, s1, s2, _i, _ref;
    args = Array.prototype.slice.call(arguments);
    s0 = 0;
    s1 = 0;
    s2 = 0;
    c = 1;
    if (args.length === 0) {
      args = [+(new Date)];
    }
    mash = new Mash();
    s0 = mash.hash(' ');
    s1 = mash.hash(' ');
    s2 = mash.hash(' ');
    for (i = _i = 0, _ref = args.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      s0 -= mash.hash(args[i]);
      if (s0 < 0) {
        s0 += 1;
      }
      s1 -= mash.hash(args[i]);
      if (s1 < 0) {
        s1 += 1;
      }
      s2 -= mash.hash(args[i]);
      if (s2 < 0) {
        s2 += 1;
      }
    }
    mash = null;
    /*
       * @returns {Number} the next random number as determined by the seed
    */

    this.random = function() {
      var t;
      t = 2091639 * s0 + c * 2.3283064365386963e-10;
      s0 = s1;
      s1 = s2;
      return s2 = t - (c = t | 0);
    };
    return this;
  };

}).call(this);
