// Generated by CoffeeScript 1.4.0

/*
 * @fileoverview
 * Base64 encode / decode
 * @author http://www.webtoolkit.info
*/


(function() {
  var decode, keyStr;

  keyStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";

  /*
   * Decodes a base64 encoded string to a string.
  */


  decode = exports.decode = function(input) {
    var chr1, chr2, chr3, enc1, enc2, enc3, enc4, i, output;
    output = [];
    i = 0;
    input = input.replace(/[^A-Za-z0-9\+\/\=]/g, "");
    while (i < input.length) {
      enc1 = keyStr.indexOf(input.charAt(i++));
      enc2 = keyStr.indexOf(input.charAt(i++));
      enc3 = keyStr.indexOf(input.charAt(i++));
      enc4 = keyStr.indexOf(input.charAt(i++));
      chr1 = (enc1 << 2) | (enc2 >> 4);
      chr2 = ((enc2 & 15) << 4) | (enc3 >> 2);
      chr3 = ((enc3 & 3) << 6) | enc4;
      output.push(String.fromCharCode(chr1));
      if (enc3 !== 64) {
        output.push(String.fromCharCode(chr2));
      }
      if (enc4 !== 64) {
        output.push(String.fromCharCode(chr3));
      }
    }
    output = output.join('');
    return output;
  };

  /*
   * Decodes a base64 encoded string into a byte array
   * @param {String} input
   * @param {Array} bytes bytes per character, defaults to 1
  */


  exports.decodeAsArray = function(input, bytes) {
    var array, decoded, i, j, len, _i, _j, _ref, _ref1;
    bytes = bytes || 1;
    decoded = decode(input);
    len = decoded.length / bytes;
    array = [];
    for (i = _i = 0, _ref = len - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      array[i] = 0;
      for (j = _j = _ref1 = bytes - 1; _ref1 <= 0 ? _j <= 0 : _j >= 0; j = _ref1 <= 0 ? ++_j : --_j) {
        array[i] += decoded.charCodeAt((i * bytes) + j) << (j << 3);
      }
    }
    return array;
  };

}).call(this);
